"""Air purifier command and model capability constants.

This module is intentionally Home Assistant independent. ``core.const`` imports
and re-exports these symbols for backward compatibility.
"""

from __future__ import annotations

AIRPURIFIER_POWER = "0x00"

AIRPURIFIER_OPERATING_MODE = "0x01"

AIRPURIFIER_TIMER_ON = "0x02"

AIRPURIFIER_TIMER_OFF = "0x03"

AIRPURIFIER_AIR_QUALITY = "0x04"

AIRPURIFIER_RESET_FILTER_NOTIFY = "0x05"

AIRPURIFIER_HEAP_REPLACE_NOTIFY = "0x06"

AIRPURIFIER_NANOEX = "0x07"

AIRPURIFIER_LOCK = "0x08"

AIRPURIFIER_ERROR_CODE = "0x09"

AIRPURIFIER_ENERGY = "0x0E"

AIRPURIFIER_PM25 = "0x50"

AIRPURIFIER_51 = "0x51"

AIRPURIFIER_52 = "0x52"

AIRPURIFIER_TIMER_OFF_NEW = "0x53"

AIRPURIFIER_FORMALDEHYDE = "0x54"

AIRPURIFIER_PET_MODE = "0x55"

AIRPURIFIER_LIGHT = "0x56"

AIRPURIFIER_BUZZER = "0x57"

AIRPURIFIER_RUNNING_TIME = "0x63"

AIRPURIFIER_RESERVED = "0x7F"

AIRPURIFIER_NANOEX_PRESET = "nanoe™ X"

AIRPURIFIER_PRESET_MODES = {
    AIRPURIFIER_NANOEX: AIRPURIFIER_NANOEX_PRESET,
}
