"""Shared Home Assistant-independent Panasonic EMS2 constants."""

ENTITY_UPDATE = "0xB0"
ENTITY_EMPTY = "0xFF"

ENTITY_MONTHLY_ENERGY = "0xA1"
ENTITY_DOOR_OPENS = "0xA2"
ENTITY_WATER_USED = "0xA2"
ENTITY_WASH_TIMES = "0xA3"
ENTITY_UPDATE_INFO = "0xB1"

DEVICE_TYPE_CLIMATE = 1
DEVICE_TYPE_FRIDGE = 2
DEVICE_TYPE_WASHING_MACHINE = 3
DEVICE_TYPE_DEHUMIDIFIER = 4
DEVICE_TYPE_DRYER = 6
DEVICE_TYPE_AIRPURIFIER = 8
DEVICE_TYPE_ERV = 14
DEVICE_TYPE_FAN = 15
DEVICE_TYPE_LIGHT = 17
DEVICE_TYPE_WEIGHT_PLATE = 23
