"""Dehumidifier command and model capability constants.

This module is intentionally Home Assistant independent. ``core.const`` imports
and re-exports these symbols for backward compatibility.
"""

from __future__ import annotations

DEHUMIDIFIER_POWER = "0x00"

DEHUMIDIFIER_MODE = "0x01"

DEHUMIDIFIER_TIMER_OFF = "0x02"

DEHUMIDIFIER_RELATIVE_HUMIDITY = "0x03"

DEHUMIDIFIER_TARGET_HUMIDITY = "0x04"

DEHUMIDIFIER_HUMIDITY_INDOOR = "0x07"

DEHUMIDIFIER_FAN_SPEED = "0x09"

DEHUMIDIFIER_WATER_TANK_STATUS = "0x0A"

DEHUMIDIFIER_FILTER_CLEAN = "0x0B"

DEHUMIDIFIER_AIRFRESH_MODE = "0x0D"

DEHUMIDIFIER_FAN_MODE = "0x0E"

DEHUMIDIFIER_ERROR_CODE = "0x12"

DEHUMIDIFIER_BUZZER = "0x18"

DEHUMIDIFIER_ENERGY = "0x1D"

DEHUMIDIFIER_50 = "0x50"

DEHUMIDIFIER_51 = "0x51"

DEHUMIDIFIER_PM25 = "0x53"

DEHUMIDIFIER_TIMER_ON = "0x55"

DEHUMIDIFIER_PM10 = "0x56"

DEHUMIDIFIER_58 = "0x58"

DEHUMIDIFIER_59 = "0x59"

DEHUMIDIFIER_MAX_HUMIDITY = 70

DEHUMIDIFIER_MIN_HUMIDITY = 40

DEHUMIDIFIER_DEFAULT_MODES = {
    "Auto": 0,
    "Set": 1,
    "Continuous": 2,
    "Cloth Dry": 3
}

DEHUMIDIFIER_PERFORMANCE_MODELS = ["KBS", "LMS", "NM"]

DEHUMIDIFIER_GHW_COMMANDS = []

DEHUMIDIFIER_JHW_COMMANDS = [
    DEHUMIDIFIER_ERROR_CODE,
#    DEHUMIDIFIER_51,
    DEHUMIDIFIER_PM25,
    DEHUMIDIFIER_PM10,
    DEHUMIDIFIER_58,
#    DEHUMIDIFIER_59
]
