"""Washing machine command and model capability constants.

This module is intentionally Home Assistant independent. ``core.const`` imports
and re-exports these symbols for backward compatibility.
"""

from __future__ import annotations

from .common import (
    DEVICE_TYPE_WASHING_MACHINE,
    ENTITY_UPDATE,
    ENTITY_WASH_TIMES,
    ENTITY_WATER_USED,
)

WASHING_MACHINE_POWER = "0x00"

WASHING_MACHINE_ENABLE = "0x01"

WASHING_MACHINE_PROGRESS = "0x02"

WASHING_MACHINE_OPERATING_STATUS_OLD = "0x03"

WASHING_MACHINE_REMAING_WASH_TIME= "0x13"

WASHING_MACHINE_TIMER = "0x14"

WASHING_MACHINE_TIMER_REMAINING_TIME_OLD = "0x15"

WASHING_MACHINE_ERROR_CODE = "0x19"

WASHING_MACHINE_ERROR_STATUS = "0x20"

WASHING_MACHINE_PROGRAM_1 = "0x34"

WASHING_MACHINE_LX128_REMAINING_WASH_TIME = "0x41"

WASHING_MACHINE_NANOE_REMAINING_TIME = "0x4F"

WASHING_MACHINE_ENERGY = "0x1E"

WASHING_MACHINE_OPERATING_STATUS = "0x50"

WASHING_MACHINE_51 = "0x51"

WASHING_MACHINE_52 = "0x52"

WASHING_MACHINE_53 = "0x53"

WASHING_MACHINE_CURRENT_MODE = "0x54"

WASHING_MACHINE_CURRENT_PROGRESS = "0x55"

WASHING_MACHINE_POSTPONE_DRYING = "0x56"

WASHING_MACHINE_57 = "0x57"

WASHING_MACHINE_TIMER_REMAINING_TIME = "0x58"

WASHING_MACHINE_59 = "0x59"

WASHING_MACHINE_60 = "0x60"

WASHING_MACHINE_DRYING_TIME = "0x49"

WASHING_MACHINE_DRYING_METHOD = "0x4C"

WASHING_MACHINE_61 = "0x61"

WASHING_MACHINE_POSTPONE_DRYING_TIME = WASHING_MACHINE_61

WASHING_MACHINE_PROGRESS_NEW = "0x64"

WASHING_MACHINE_66 = "0x66"

WASHING_MACHINE_67 = "0x67"

WASHING_MACHINE_68 = "0x68"

WASHING_MACHINE_WARM_WATER = "0x69"

WASHING_MACHINE_71 = "0x71"

WASHING_MACHINE_72 = "0x72"

WASHING_MACHINE_73 = "0x73"

WASHING_MACHINE_REMOTE_CONTROL = "0x74"

WASHING_MACHINE_DETERGENT_AMOUNT = "0x76"

WASHING_MACHINE_SOFTENER_AMOUNT = "0x77"

WASHING_MACHINE_MODELS = ["DDH", "DW","HDH", "MDH"]

WASHING_MACHINE_2020_MODELS = ["KBS", "LM", "LMS"]

WASHING_MACHINE_LX128B_COMMANDS = [
    WASHING_MACHINE_71,
    WASHING_MACHINE_72,
    WASHING_MACHINE_73
]

WASHING_MACHINE_LX128_COMMANDS = [
    WASHING_MACHINE_CURRENT_PROGRESS,
    WASHING_MACHINE_OPERATING_STATUS,
    WASHING_MACHINE_CURRENT_MODE,
    WASHING_MACHINE_LX128_REMAINING_WASH_TIME,
    WASHING_MACHINE_NANOE_REMAINING_TIME,
    WASHING_MACHINE_TIMER_REMAINING_TIME_OLD,
    WASHING_MACHINE_ERROR_STATUS,
    WASHING_MACHINE_TIMER,
    WASHING_MACHINE_60,
    WASHING_MACHINE_POSTPONE_DRYING_TIME,
    WASHING_MACHINE_PROGRESS_NEW,
]

WASHING_MACHINE_HDH_COMMANDS = [
    # HDH 遠端 CommandList（2026-06-26 只讀確認）有列出、但共用 base 未包含的主包 keys。
    # 主 DeviceGetInfo 只放遠端 metadata 正式宣告的 command，避免重演冷氣全量輪詢 timeout 問題。
    WASHING_MACHINE_TIMER_REMAINING_TIME_OLD,
    WASHING_MACHINE_60,
    WASHING_MACHINE_POSTPONE_DRYING_TIME,
    WASHING_MACHINE_PROGRESS_NEW,
]

WASHING_MACHINE_HDH_NON_COMMANDLIST_COMMANDS = [
    # 以下 key 不在 HDH 遠端 CommandList；不可留在主包，避免 DeviceGetInfo 大包 timeout。
    WASHING_MACHINE_TIMER_REMAINING_TIME,
    WASHING_MACHINE_ENERGY,
    WASHING_MACHINE_POSTPONE_DRYING,
    WASHING_MACHINE_52,
    WASHING_MACHINE_66,
    WASHING_MACHINE_67,
    WASHING_MACHINE_REMOTE_CONTROL,
    WASHING_MACHINE_DETERGENT_AMOUNT,
    WASHING_MACHINE_SOFTENER_AMOUNT,
]

WASHING_MACHINE_HDH_SUPPLEMENTAL_COMMANDS = [
    # 以下 key 不在 HDH 遠端 CommandList，但已由實機小包 DeviceGetInfo / observation 確認可讀；改走 supplemental 小包。
    WASHING_MACHINE_TIMER_REMAINING_TIME,  # 0x58：預約洗衣完成時間（分鐘），僅在 0x50=預約中 時有語意。
    WASHING_MACHINE_ENERGY,                # 0x1E：用電量；不在 HDH CommandList，改用 supplemental 小包。
    WASHING_MACHINE_REMOTE_CONTROL,        # 0x74：遠端遙控，1 為開啟、0 為關閉。
    WASHING_MACHINE_DETERGENT_AMOUNT,      # 0x76：洗劑投入設定 mL。
    WASHING_MACHINE_SOFTENER_AMOUNT,       # 0x77：柔軟劑投入設定 mL。

    # 0xA2/0xA3/0xB0 是非 DeviceGetInfo 來源的補充顯示 key；
    # 它們分別由 UserGetInfo / UpdateCheck 補進 Information，不放進此清單，避免錯誤呼叫 DeviceGetInfo。

    # 以下 key 目前不是 HDH 遠端 CommandList 主包，且語意或穩定性尚未確認；先不要常態讀取。
    # WASHING_MACHINE_OPERATING_STATUS_OLD,      # 0x03：舊式狀態欄位，與 0x50 關係未確認。
    # WASHING_MACHINE_POSTPONE_DRYING,           # 0x56：延後晾衣狀態/設定語意未確認。
    # WASHING_MACHINE_52,                        # 0x52：未知欄位，尚未對應官方 App 顯示。
    # WASHING_MACHINE_53,                        # 0x53：未知欄位，尚未對應官方 App 顯示。
    # WASHING_MACHINE_57,                        # 0x57：未知欄位，尚未對應官方 App 顯示。
    # WASHING_MACHINE_66,                        # 0x66：未知欄位，尚未對應官方 App 顯示。
    # WASHING_MACHINE_67,                        # 0x67：未知欄位，尚未對應官方 App 顯示。
]

WASHING_MACHINE_HDH_SUPPLEMENTAL_DISPLAY_KEYS = [
    # HDH 顯示層 supplemental：包含 DeviceGetInfo supplemental 與非 DeviceGetInfo 補充資訊。
    WASHING_MACHINE_TIMER_REMAINING_TIME,
    WASHING_MACHINE_ENERGY,
    WASHING_MACHINE_REMOTE_CONTROL,
    WASHING_MACHINE_DETERGENT_AMOUNT,
    WASHING_MACHINE_SOFTENER_AMOUNT,
    ENTITY_WATER_USED,   # 0xA2：當月用水量，由 UserGetInfo 補入。
    ENTITY_WASH_TIMES,   # 0xA3：當月洗衣次數，由 UserGetInfo 補入。
    ENTITY_UPDATE,       # 0xB0：版本更新，由 UpdateCheck 補入。
]

COMMAND_NAME_OVERRIDES = {
    str(DEVICE_TYPE_WASHING_MACHINE): {
        WASHING_MACHINE_REMAING_WASH_TIME: "預估洗衣完成時間",
        WASHING_MACHINE_TIMER_REMAINING_TIME_OLD: "預約洗衣開始時間",
        WASHING_MACHINE_TIMER_REMAINING_TIME: "預約洗衣完成時間",
        WASHING_MACHINE_CURRENT_MODE: "目前洗衣行程",
        WASHING_MACHINE_CURRENT_PROGRESS: "洗衣行程設定",
        WASHING_MACHINE_REMOTE_CONTROL: "遠端遙控",
    }
}

COMMAND_RANGE_OVERRIDES = {
    str(DEVICE_TYPE_WASHING_MACHINE): {
        WASHING_MACHINE_REMOTE_CONTROL: {
            "關閉": 0,
            "開啟": 1,
        },
    }
}

WASHING_MACHINE_CLOCK_TIME_KEYS = [
    WASHING_MACHINE_REMAING_WASH_TIME,
    WASHING_MACHINE_TIMER_REMAINING_TIME_OLD,
    WASHING_MACHINE_TIMER_REMAINING_TIME,
]

WASHING_MACHINE_ACTIVE_FINISH_TIME_KEYS = [
    WASHING_MACHINE_REMAING_WASH_TIME,
]

WASHING_MACHINE_RESERVATION_CLOCK_TIME_KEYS = [
    WASHING_MACHINE_TIMER_REMAINING_TIME_OLD,
    WASHING_MACHINE_TIMER_REMAINING_TIME,
]

WASHING_MACHINE_ACTIVE_OPERATING_STATUS_VALUES = [2]

WASHING_MACHINE_RESERVATION_OPERATING_STATUS_VALUES = [3, 4]

WASHING_MACHINE_KBS_COMMANDS = [
    WASHING_MACHINE_TIMER_REMAINING_TIME_OLD
]
