"""Constants of the Panasonic Smart Home component."""

from .capabilities import build_capability_registry
from .constants.common import (
    DEVICE_TYPE_AIRPURIFIER,
    DEVICE_TYPE_CLIMATE,
    DEVICE_TYPE_DEHUMIDIFIER,
    DEVICE_TYPE_DRYER,
    DEVICE_TYPE_ERV,
    DEVICE_TYPE_FAN,
    DEVICE_TYPE_FRIDGE,
    DEVICE_TYPE_LIGHT,
    DEVICE_TYPE_WASHING_MACHINE,
    DEVICE_TYPE_WEIGHT_PLATE,
    ENTITY_DOOR_OPENS,
    ENTITY_EMPTY,
    ENTITY_MONTHLY_ENERGY,
    ENTITY_UPDATE,
    ENTITY_UPDATE_INFO,
    ENTITY_WASH_TIMES,
    ENTITY_WATER_USED,
)
from .entity_descriptions.base import (
    PanasonicBinarySensorDescription,
    PanasonicNumberDescription,
    PanasonicSelectDescription,
    PanasonicSensorDescription,
    PanasonicSwitchDescription,
)
from .entity_descriptions.climate import (
    CLIMATE_BINARY_SENSORS,
    CLIMATE_NUMBERS,
    CLIMATE_SELECTS,
    CLIMATE_SENSORS,
    CLIMATE_SWITCHES,
)
from .constants.climate import (
    CLIMATE_POWER,
    CLIMATE_OPERATING_MODE,
    CLIMATE_FAN_SPEED,
    CLIMATE_TARGET_TEMPERATURE,
    CLIMATE_TEMPERATURE_INDOOR,
    CLIMATE_SLEEP_MODE,
    CLIMATE_FUZZY_MODE,
    CLIMATE_AIRFRESH_MODE,
    CLIMATE_TIMER_ON,
    CLIMATE_TIMER_OFF,
    CLIMATE_SWING_VERTICAL,
    CLIMATE_SWING_VERTICAL_LEVEL,
    CLIMATE_SWING_HORIZONTAL,
    CLIMATE_SWING_HORIZONTAL_LEVEL,
    CLIMATE_SET_HUMIDITY,
    CLIMATE_HUMIDITY_INDOOR,
    CLIMATE_ERROR_CODE,
    CLIMATE_ANTI_MILDEW,
    CLIMATE_AUTO_CLEAN,
    CLIMATE_ACTIVITY,
    CLIMATE_BOOST,
    CLIMATE_ECO,
    CLIMATE_COMFORT,
    CLIMATE_BUZZER,
    CLIMATE_INDICATOR_LIGHT,
    CLIMATE_TEMPERATURE_OUTDOOR,
    CLIMATE_OPERATING_POWER,
    CLIMATE_ENERGY,
    CLIMATE_PM25,
    CLIMATE_MONITOR_MILDEW,
    CLIMATE_IMMEDIATE_MILDEW_DRY,
    CLIMATE_VOICE,
    CLIMATE_61,
    CLIMATE_RESERVED,
    CLIMATE_PRESET_MODE,
    CLIMATE_SWING_MODE,
    CLIMATE_RX_COMMANDS,
    CLIMATE_PXGD_COMMMANDS,
    CLIMATE_PXGD_SUPPLEMENTAL_COMMANDS,
    CLIMATE_VX_COMMMANDS,
    CLIMATE_UX_COMMMANDS,
    CLIMATE_UJ_COMMMANDS,
    CLIMATE_UK_COMMMANDS,
    CLIMATE_VX_SUPPLEMENTAL_COMMANDS,
    CLIMATE_UX_SUPPLEMENTAL_COMMANDS,
    CLIMATE_UJ_SUPPLEMENTAL_COMMANDS,
    CLIMATE_UK_SUPPLEMENTAL_COMMANDS,
    CLIMATE_PXGD_MODELS,
    CLIMATE_PM10_MODELS,
    CLIMATE_PM10_2_MODELS,
    CLIMATE_PM25_MODELS,
    CLIMATE_RANGE_FAMILY,
)

from .constants.airpurifier import (
    AIRPURIFIER_POWER,
    AIRPURIFIER_OPERATING_MODE,
    AIRPURIFIER_TIMER_ON,
    AIRPURIFIER_TIMER_OFF,
    AIRPURIFIER_AIR_QUALITY,
    AIRPURIFIER_RESET_FILTER_NOTIFY,
    AIRPURIFIER_HEAP_REPLACE_NOTIFY,
    AIRPURIFIER_NANOEX,
    AIRPURIFIER_LOCK,
    AIRPURIFIER_ERROR_CODE,
    AIRPURIFIER_ENERGY,
    AIRPURIFIER_PM25,
    AIRPURIFIER_51,
    AIRPURIFIER_52,
    AIRPURIFIER_TIMER_OFF_NEW,
    AIRPURIFIER_FORMALDEHYDE,
    AIRPURIFIER_PET_MODE,
    AIRPURIFIER_LIGHT,
    AIRPURIFIER_BUZZER,
    AIRPURIFIER_RUNNING_TIME,
    AIRPURIFIER_RESERVED,
    AIRPURIFIER_NANOEX_PRESET,
    AIRPURIFIER_PRESET_MODES,
)
from .constants.dehumidifier import (
    DEHUMIDIFIER_POWER,
    DEHUMIDIFIER_MODE,
    DEHUMIDIFIER_TIMER_OFF,
    DEHUMIDIFIER_RELATIVE_HUMIDITY,
    DEHUMIDIFIER_TARGET_HUMIDITY,
    DEHUMIDIFIER_HUMIDITY_INDOOR,
    DEHUMIDIFIER_FAN_SPEED,
    DEHUMIDIFIER_WATER_TANK_STATUS,
    DEHUMIDIFIER_FILTER_CLEAN,
    DEHUMIDIFIER_AIRFRESH_MODE,
    DEHUMIDIFIER_FAN_MODE,
    DEHUMIDIFIER_ERROR_CODE,
    DEHUMIDIFIER_BUZZER,
    DEHUMIDIFIER_ENERGY,
    DEHUMIDIFIER_50,
    DEHUMIDIFIER_51,
    DEHUMIDIFIER_PM25,
    DEHUMIDIFIER_TIMER_ON,
    DEHUMIDIFIER_PM10,
    DEHUMIDIFIER_58,
    DEHUMIDIFIER_59,
    DEHUMIDIFIER_MAX_HUMIDITY,
    DEHUMIDIFIER_MIN_HUMIDITY,
    DEHUMIDIFIER_DEFAULT_MODES,
    DEHUMIDIFIER_PERFORMANCE_MODELS,
    DEHUMIDIFIER_GHW_COMMANDS,
    DEHUMIDIFIER_JHW_COMMANDS,
)
from .constants.dryer import (
    DRYER_POWER,
    DRYER_OPERATING_STATUS,
    DRYER_HEATING_STATUS,
    DRYER_OPERATING_MODE,
    DRYER_OPERATING_TIME,
    DRYER_REMAINING_TIME,
    DRYER_STATUS,
    DRYER_DISPLAY,
    DRYER_FAN_SPEED,
    DRYER_TEMPERATURE,
    DRYER_ERROR_CODE,
    DRYER_ENERGY,
    DRYER_APPOINTMENT_REMAINING_TIME,
    DRYER_PROGRAM_1,
    DRYER_OPERATING_STATUS_NEW,
    DRYER_OPERATING_MODE_NEW,
    DRYER_PROGRAM_2,
)
from .constants.erv import (
    ERV_POWER,
    ERV_OPERATING_MODE,
    ERV_FAN_SPEED,
    ERV_TARGET_TEMPERATURE,
    ERV_TEMPERATURE_IN,
    ERV_TEMPERATURE_OUT,
    ERV_TIMER_ON,
    ERV_ERROR_CODE,
    ERV_ENERGY,
    ERV_RESET_FILTER_NOTIFY,
    ERV_VENTILATE_MODE,
    ERV_PRE_HEAT_COOL,
    ERV_REVERED,
    ERV_MINIMUM_TEMPERATURE,
    ERV_MAXIMUM_TEMPERATURE,
    ERV_AVAILABLE_MODES,
    ERV_AVAILABLE_FAN_MODES,
)
from .constants.fan import (
    FAN_POWER,
    FAN_OPERATING_MODE,
    FAN_SPEED,
    FAN_TEMPERATURE_INDOOR,
    FAN_OSCILLATE,
    FAN_PRESET_MODES,
)
from .constants.fridge import (
    FRIDGE_FREEZER_MODE,
    FRIDGE_CHAMBER_MODE,
    FRIDGE_FREEZER_TEMPERATURE,
    FRIDGE_CHAMBER_TEMPERATURE,
    FRIDGE_ECO,
    FRIDGE_ERROR_CODE,
    FRIDGE_ENERGY,
    FRIDGE_DEFROST_SETTING,
    FRIDGE_STOP_ICE_MAKING,
    FRIDGE_FAST_ICE_MAKING,
    FRIDGE_FRESH_QUICK_FREZZE,
    FRIDGE_THAW_MODE,
    FRIDGE_THAW_TEMPERATURE,
    FRIDGE_WINTER_MDOE,
    FRIDGE_SHOPPING_MODE,
    FRIDGE_GO_OUT_MODE,
    FRIDGE_NANOEX,
    FRIDGE_ERROR_CODE_JP,
    FRIDGE_XGS_COMMANDS,
    FRIDGE_MODELS,
    FRIDGE_2020_MODELS,
)
from .constants.light import (
    LIGHT_POWER,
    LIGHT_PERCENTAGE,
    LIGHT_OPERATION_STATE,
    LIGHT_CHANNEL_1_TIMER_ON,
    LIGHT_CHANNEL_1_TIMER_OFF,
    LIGHT_MAINTAIN_MODE,
    LIGHT_CHANNEL_2_TIMER_ON,
    LIGHT_CHANNEL_2_TIMER_OFF,
    LIGHT_CHANNEL_3_TIMER_ON,
    LIGHT_CHANNEL_3_TIMER_OFF,
    LIGHT_RESERVED,
    LIGHT_WTY_COMMANDS,
)
from .constants.washing_machine import (
    WASHING_MACHINE_POWER,
    WASHING_MACHINE_ENABLE,
    WASHING_MACHINE_PROGRESS,
    WASHING_MACHINE_OPERATING_STATUS_OLD,
    WASHING_MACHINE_REMAING_WASH_TIME,
    WASHING_MACHINE_TIMER,
    WASHING_MACHINE_TIMER_REMAINING_TIME_OLD,
    WASHING_MACHINE_ERROR_CODE,
    WASHING_MACHINE_ENERGY,
    WASHING_MACHINE_OPERATING_STATUS,
    WASHING_MACHINE_51,
    WASHING_MACHINE_52,
    WASHING_MACHINE_53,
    WASHING_MACHINE_CURRENT_MODE,
    WASHING_MACHINE_CURRENT_PROGRESS,
    WASHING_MACHINE_POSTPONE_DRYING,
    WASHING_MACHINE_57,
    WASHING_MACHINE_TIMER_REMAINING_TIME,
    WASHING_MACHINE_59,
    WASHING_MACHINE_60,
    WASHING_MACHINE_61,
    WASHING_MACHINE_POSTPONE_DRYING_TIME,
    WASHING_MACHINE_PROGRESS_NEW,
    WASHING_MACHINE_66,
    WASHING_MACHINE_67,
    WASHING_MACHINE_68,
    WASHING_MACHINE_WARM_WATER,
    WASHING_MACHINE_71,
    WASHING_MACHINE_72,
    WASHING_MACHINE_73,
    WASHING_MACHINE_REMOTE_CONTROL,
    WASHING_MACHINE_DETERGENT_AMOUNT,
    WASHING_MACHINE_SOFTENER_AMOUNT,
    WASHING_MACHINE_MODELS,
    WASHING_MACHINE_2020_MODELS,
    WASHING_MACHINE_LX128B_COMMANDS,
    WASHING_MACHINE_HDH_COMMANDS,
    WASHING_MACHINE_HDH_NON_COMMANDLIST_COMMANDS,
    WASHING_MACHINE_HDH_SUPPLEMENTAL_COMMANDS,
    WASHING_MACHINE_HDH_SUPPLEMENTAL_DISPLAY_KEYS,
    COMMAND_NAME_OVERRIDES,
    COMMAND_RANGE_OVERRIDES,
    WASHING_MACHINE_CLOCK_TIME_KEYS,
    WASHING_MACHINE_ACTIVE_FINISH_TIME_KEYS,
    WASHING_MACHINE_RESERVATION_CLOCK_TIME_KEYS,
    WASHING_MACHINE_ACTIVE_OPERATING_STATUS_VALUES,
    WASHING_MACHINE_RESERVATION_OPERATING_STATUS_VALUES,
    WASHING_MACHINE_KBS_COMMANDS,
)
from .constants.weight_plate import (
    WEIGHT_PLATE_GET_WEIGHT,
    WEIGHT_PLATE_FOOD_NAME,
    WEIGHT_PLATE_MANAGEMENT_MODE,
    WEIGHT_PLATE_MANAGEMENT_VALUE,
    WEIGHT_PLATE_AMOUNT_MAX,
    WEIGHT_PLATE_BUY_DATE,
    WEIGHT_PLATE_DUE_DATE,
    WEIGHT_PLATE_COMMUNICATION_MODE,
    WEIGHT_PLATE_COMMUNICATION_TIME,
    WEIGHT_PLATE_TOTAL_WEIGHT,
    WEIGHT_PLATE_RESTORE_WEIGHT,
    WEIGHT_PLATE_LOW_BATTERY,
)

from .entity_descriptions.airpurifier import (
    AIRPURIFIER_BINARY_SENSORS,
    AIRPURIFIER_NUMBERS,
    AIRPURIFIER_SELECTS,
    AIRPURIFIER_SENSORS,
    AIRPURIFIER_SWITCHES,
)
from .entity_descriptions.dehumidifier import (
    DEHUMIDIFIER_BINARY_SENSORS,
    DEHUMIDIFIER_NUMBERS,
    DEHUMIDIFIER_SELECTS,
    DEHUMIDIFIER_SENSORS,
    DEHUMIDIFIER_SWITCHES,
)
from .entity_descriptions.dryer import (
    DRYER_BINARY_SENSORS,
    DRYER_NUMBERS,
    DRYER_SELECTS,
    DRYER_SENSORS,
)
from .entity_descriptions.erv import (
    ERV_BINARY_SENSORS,
    ERV_NUMBERS,
    ERV_SELECTS,
    ERV_SENSORS,
)
from .entity_descriptions.fridge import (
    FRIDGE_BINARY_SENSORS,
    FRIDGE_SELECTS,
    FRIDGE_SENSORS,
    FRIDGE_SWITCHES,
)
from .entity_descriptions.light import (
    LIGHT_BINARY_SENSORS,
    LIGHT_NUMBERS,
    LIGHT_SENSORS,
    LIGHT_SWITCHES,
)
from .entity_descriptions.washing_machine import (
    WASHING_MACHINE_BINARY_SENSORS,
    WASHING_MACHINE_HDH_SELECTS,
    WASHING_MACHINE_SELECTS_BY_MODEL,
    WASHING_MACHINE_SELECTS,
    WASHING_MACHINE_SENSORS,
    WASHING_MACHINE_SWITCHES,
)
from .entity_descriptions.weight_plate import (
    WEIGHT_PLATE_SENSORS,
)

from homeassistant.components.binary_sensor import (
    BinarySensorDeviceClass
)

from homeassistant.components.sensor import (
    SensorDeviceClass,
    SensorStateClass
)

from homeassistant.components.switch import (
    SwitchDeviceClass
)

from homeassistant.components.climate.const import (
    HVACMode,
    PRESET_BOOST,
    PRESET_ECO,
    PRESET_COMFORT,
    PRESET_SLEEP,
    PRESET_ACTIVITY,
    SWING_ON,
    SWING_OFF,
    SWING_BOTH,
    SWING_VERTICAL,
    SWING_HORIZONTAL
)
from homeassistant.const import (
    EntityCategory,
    CONCENTRATION_MICROGRAMS_PER_CUBIC_METER,
    CONCENTRATION_PARTS_PER_BILLION,
    PERCENTAGE,
    UnitOfEnergy,
    UnitOfMass,
    UnitOfTemperature,
    UnitOfTime,
    UnitOfVolume
)

DOMAIN = "panasonic_ems2"

DOMAINS = [
    "binary_sensor",
    "climate",
    "fan",
    "humidifier",
    "number",
    "sensor",
    "select",
    "switch"
]

HA_USER_AGENT = "Mozilla/5.0 (iPhone; CPU iPhone OS 17_1 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/17.1 Mobile/15E148 Safari/604.1"
BASE_URL = 'https://ems2.panasonic.com.tw/api'
APP_TOKEN = "D8CBFF4C-2824-4342-B22D-189166FEF503"

DATA_CLIENT = "client"
DATA_COORDINATOR = "coordinator"

CONF_UPDATE_INTERVAL = "update_interval"
CONF_CPTOKEN = "cptoken"
CONF_TOKEN_TIMEOUT = "cptoken_timeout"
CONF_REFRESH_TOKEN = "refresh_token"
CONF_REFRESH_TOKEN_TIMEOUT = "refresh_token_timeout"

DEFAULT_UPDATE_INTERVAL = 120
REQUEST_TIMEOUT = 15

DATA_CLIENT = "client"
DATA_COORDINATOR = "coordinator"
UPDATE_LISTENER = "update_listener"

USER_INFO_TYPES = [
#    "Power",
#    "Temp",
#    "Humid",
#    "PM",
    "Other"
]


USER_INFO_SERIES_STORAGE = "UserInfoSeries"
USER_INFO_SERIES_REFRESH_SECONDS = 3600
USER_INFO_SERIES_RANGES = {
    "today": "當日",
    "current_month": "當月",
    "current_year": "當年",
    "last_30_days": "近30日",
    "last_12_months": "近1年",
}

ENTITY_MONTHLY_ENERGY_TODAY = "0xA0_today"
ENTITY_MONTHLY_ENERGY_CURRENT_MONTH = "0xA0_current_month"
ENTITY_MONTHLY_ENERGY_CURRENT_YEAR = "0xA0_current_year"
ENTITY_MONTHLY_ENERGY_LAST_30_DAYS = "0xA0_last_30_days"
ENTITY_MONTHLY_ENERGY_LAST_12_MONTHS = "0xA0_last_12_months"

ENTITY_WATER_USED_TODAY = "0xA2_today"
ENTITY_WATER_USED_CURRENT_MONTH = "0xA2_current_month"
ENTITY_WATER_USED_CURRENT_YEAR = "0xA2_current_year"
ENTITY_WATER_USED_LAST_30_DAYS = "0xA2_last_30_days"
ENTITY_WATER_USED_LAST_12_MONTHS = "0xA2_last_12_months"

ENTITY_WASH_TIMES_TODAY = "0xA3_today"
ENTITY_WASH_TIMES_CURRENT_MONTH = "0xA3_current_month"
ENTITY_WASH_TIMES_CURRENT_YEAR = "0xA3_current_year"
ENTITY_WASH_TIMES_LAST_30_DAYS = "0xA3_last_30_days"
ENTITY_WASH_TIMES_LAST_12_MONTHS = "0xA3_last_12_months"

USER_INFO_POWER_SERIES_KEYS = [
    ENTITY_MONTHLY_ENERGY_TODAY,
    ENTITY_MONTHLY_ENERGY_CURRENT_MONTH,
    ENTITY_MONTHLY_ENERGY_CURRENT_YEAR,
    ENTITY_MONTHLY_ENERGY_LAST_30_DAYS,
    ENTITY_MONTHLY_ENERGY_LAST_12_MONTHS,
]
USER_INFO_WATER_SERIES_KEYS = [
    ENTITY_WATER_USED_TODAY,
    ENTITY_WATER_USED_CURRENT_MONTH,
    ENTITY_WATER_USED_CURRENT_YEAR,
    ENTITY_WATER_USED_LAST_30_DAYS,
    ENTITY_WATER_USED_LAST_12_MONTHS,
]
USER_INFO_WASH_TIMES_SERIES_KEYS = [
    ENTITY_WASH_TIMES_TODAY,
    ENTITY_WASH_TIMES_CURRENT_MONTH,
    ENTITY_WASH_TIMES_CURRENT_YEAR,
    ENTITY_WASH_TIMES_LAST_30_DAYS,
    ENTITY_WASH_TIMES_LAST_12_MONTHS,
]
USER_INFO_SERIES_KEYS = [
    ENTITY_MONTHLY_ENERGY_TODAY,
    ENTITY_MONTHLY_ENERGY_CURRENT_MONTH,
    ENTITY_MONTHLY_ENERGY_CURRENT_YEAR,
    ENTITY_MONTHLY_ENERGY_LAST_30_DAYS,
    ENTITY_MONTHLY_ENERGY_LAST_12_MONTHS,
    ENTITY_WATER_USED_TODAY,
    ENTITY_WATER_USED_CURRENT_MONTH,
    ENTITY_WATER_USED_CURRENT_YEAR,
    ENTITY_WATER_USED_LAST_30_DAYS,
    ENTITY_WATER_USED_LAST_12_MONTHS,
    ENTITY_WASH_TIMES_TODAY,
    ENTITY_WASH_TIMES_CURRENT_MONTH,
    ENTITY_WASH_TIMES_CURRENT_YEAR,
    ENTITY_WASH_TIMES_LAST_30_DAYS,
    ENTITY_WASH_TIMES_LAST_12_MONTHS,
]


#AIRPURIFIER_LIGHT = "0x62"


CLIMATE_AVAILABLE_MODES = {
#    HVACMode.OFF: -1,
    HVACMode.COOL: 0,
    HVACMode.DRY: 1,
    HVACMode.FAN_ONLY: 2,
    HVACMode.AUTO: 3,
    HVACMode.HEAT: 4
}

CLIMATE_AVAILABLE_SWING_MODES = [
    SWING_ON,
    SWING_OFF,
    SWING_BOTH,
    SWING_VERTICAL,
    SWING_HORIZONTAL
]
CLIMATE_AVAILABLE_FAN_MODES = {
    "Auto": 0,
    "1": 1,
    "2": 2,
    "3": 3,
    "4": 4,
    "5": 5,
    "6": 6,
    "7": 7,
    "8": 8,
    "9": 9,
    "10": 10,
    "11": 11,
    "12": 12,
    "13": 13,
    "14": 14,
    "15": 15
}
CLIMATE_MINIMUM_TEMPERATURE = 16
CLIMATE_MAXIMUM_TEMPERATURE = 30
CLIMATE_TEMPERATURE_STEP = 1.0
CLIMATE_ON_TIMER_MIN = 0
CLIMATE_ON_TIMER_MAX = 1440
CLIMATE_OFF_TIMER_MIN = 0
CLIMATE_OFF_TIMER_MAX = 1440

CLIMATE_AVAILABLE_PRESET_MODES = {
#    CLIMATE_ACTIVITY: PRESET_ACTIVITY,
    CLIMATE_BOOST: PRESET_BOOST,
#    CLIMATE_COMFORT: PRESET_COMFORT,
    CLIMATE_ECO: PRESET_ECO,
    CLIMATE_SLEEP_MODE: PRESET_SLEEP
}


MODEL_JP_TYPES = [
    "F655",
    "F656",
    "F657",
    "F658",
    "F659",
    "LX128B"
]

COMMANDS_TYPE= {
    str(DEVICE_TYPE_AIRPURIFIER): [
        AIRPURIFIER_POWER,
        AIRPURIFIER_OPERATING_MODE,
        #AIRPURIFIER_TIMER_ON,
        #AIRPURIFIER_TIMER_OFF,
        #AIRPURIFIER_AIR_QUALITY,
        AIRPURIFIER_ENERGY,
        AIRPURIFIER_HEAP_REPLACE_NOTIFY,
        AIRPURIFIER_NANOEX,
        AIRPURIFIER_PET_MODE,
        AIRPURIFIER_BUZZER,
        AIRPURIFIER_PM25,
        AIRPURIFIER_LIGHT,
        AIRPURIFIER_51,
        AIRPURIFIER_52,
        AIRPURIFIER_TIMER_OFF_NEW,
        AIRPURIFIER_FORMALDEHYDE
    ],
    str(DEVICE_TYPE_CLIMATE): [
        CLIMATE_POWER,
        CLIMATE_OPERATING_MODE,
        CLIMATE_FAN_SPEED,
        CLIMATE_TARGET_TEMPERATURE,
        CLIMATE_TEMPERATURE_INDOOR,
        CLIMATE_SLEEP_MODE,
        CLIMATE_AIRFRESH_MODE,
        CLIMATE_TIMER_ON,
        CLIMATE_TIMER_OFF,
        CLIMATE_SWING_VERTICAL_LEVEL,
        CLIMATE_SWING_HORIZONTAL_LEVEL,
        CLIMATE_ANTI_MILDEW,
        CLIMATE_AUTO_CLEAN,
        CLIMATE_ACTIVITY,
        CLIMATE_BOOST,
        CLIMATE_ECO,
        CLIMATE_BUZZER,
        CLIMATE_INDICATOR_LIGHT,
        CLIMATE_ENERGY,
        CLIMATE_TEMPERATURE_OUTDOOR
    ],
    str(DEVICE_TYPE_DEHUMIDIFIER): [
        DEHUMIDIFIER_POWER,
        DEHUMIDIFIER_MODE,
        DEHUMIDIFIER_TIMER_OFF,
        DEHUMIDIFIER_TARGET_HUMIDITY,
        DEHUMIDIFIER_HUMIDITY_INDOOR,
        DEHUMIDIFIER_FAN_SPEED,
        DEHUMIDIFIER_WATER_TANK_STATUS,
        DEHUMIDIFIER_AIRFRESH_MODE,
        DEHUMIDIFIER_FAN_MODE,
        DEHUMIDIFIER_BUZZER,
        DEHUMIDIFIER_ENERGY,
        DEHUMIDIFIER_50,
        DEHUMIDIFIER_TIMER_ON
    ],
    str(DEVICE_TYPE_DRYER): [
        DRYER_POWER,
        DRYER_OPERATING_STATUS,
        DRYER_TEMPERATURE,
        DRYER_APPOINTMENT_REMAINING_TIME,
        DRYER_HEATING_STATUS,
        DRYER_OPERATING_MODE,
        DRYER_OPERATING_TIME,
        DRYER_REMAINING_TIME,
        DRYER_STATUS,
        DRYER_FAN_SPEED,
        DRYER_OPERATING_STATUS_NEW,
        DRYER_OPERATING_MODE_NEW
    ],
    str(DEVICE_TYPE_ERV): [
        ERV_POWER,
        ERV_OPERATING_MODE,
        ERV_FAN_SPEED,
        ERV_TARGET_TEMPERATURE,
        ERV_TEMPERATURE_IN,
        ERV_TEMPERATURE_OUT,
        ERV_ERROR_CODE,
        ERV_ENERGY
    ],
    str(DEVICE_TYPE_FRIDGE): [
        FRIDGE_FREEZER_MODE,
        FRIDGE_CHAMBER_MODE,
        FRIDGE_DEFROST_SETTING,
        FRIDGE_STOP_ICE_MAKING,
        FRIDGE_FAST_ICE_MAKING,
        FRIDGE_FRESH_QUICK_FREZZE,
        FRIDGE_THAW_MODE,
        FRIDGE_WINTER_MDOE,
        FRIDGE_SHOPPING_MODE,
        FRIDGE_GO_OUT_MODE
    ],
    str(DEVICE_TYPE_LIGHT): [
        LIGHT_POWER
    ],
    str(DEVICE_TYPE_WASHING_MACHINE): [
        WASHING_MACHINE_ENABLE,
        WASHING_MACHINE_REMAING_WASH_TIME,
        WASHING_MACHINE_TIMER,
        WASHING_MACHINE_ERROR_CODE,
        WASHING_MACHINE_TIMER_REMAINING_TIME,
        WASHING_MACHINE_ENERGY,
        WASHING_MACHINE_OPERATING_STATUS,
        WASHING_MACHINE_CURRENT_MODE,
        WASHING_MACHINE_CURRENT_PROGRESS,
        WASHING_MACHINE_POSTPONE_DRYING,
        WASHING_MACHINE_WARM_WATER,
        WASHING_MACHINE_52,
        WASHING_MACHINE_66,
        WASHING_MACHINE_67,
        WASHING_MACHINE_REMOTE_CONTROL,
        WASHING_MACHINE_DETERGENT_AMOUNT,
        WASHING_MACHINE_SOFTENER_AMOUNT
    ],
    str(DEVICE_TYPE_WEIGHT_PLATE): [
        WEIGHT_PLATE_GET_WEIGHT
    ]
}

EXTRA_COMMANDS = {
    str(DEVICE_TYPE_CLIMATE): {
#        "RX-N": CLIMATE_RX_COMMANDS + [CLIMATE_MONITOR_MILDEW],
#        "PXGD": CLIMATE_PXGD_COMMMANDS,
          "VX": CLIMATE_VX_COMMMANDS,
          "UX": CLIMATE_UX_COMMMANDS,
          "UJ": CLIMATE_UJ_COMMMANDS,
          "UK": CLIMATE_UK_COMMMANDS,
          "uk": CLIMATE_UK_COMMMANDS,
        "RX-N": CLIMATE_RX_COMMANDS,
        "RX-G": CLIMATE_RX_COMMANDS,
        "RX-J": CLIMATE_RX_COMMANDS
    },
    str(DEVICE_TYPE_DEHUMIDIFIER): {
        "JHW": DEHUMIDIFIER_JHW_COMMANDS
    },
    str(DEVICE_TYPE_ERV): {
    },
    str(DEVICE_TYPE_DRYER): {
    },
    str(DEVICE_TYPE_FRIDGE): {
        "XGS": FRIDGE_XGS_COMMANDS,
        "F655": [FRIDGE_ERROR_CODE_JP],
        "F656": [FRIDGE_ERROR_CODE_JP],
        "F657": [FRIDGE_ERROR_CODE_JP],
        "F658": [FRIDGE_ERROR_CODE_JP],
        "F659": [FRIDGE_ERROR_CODE_JP]
    },
    str(DEVICE_TYPE_LIGHT): {
        "WTY": LIGHT_WTY_COMMANDS
    },
    str(DEVICE_TYPE_WASHING_MACHINE): {
        "LX128B": WASHING_MACHINE_LX128B_COMMANDS,
        "HDH": WASHING_MACHINE_HDH_COMMANDS,

        # DDH/DW/MDH 過去與 HDH 共用舊式 extra commands，但本次只遠端確認 NA-V160HDH；
        # 未確認 model 先不要套 HDH 主包補足，避免把未確認 command 放進主 DeviceGetInfo。
        # "DDH": WASHING_MACHINE_HDH_COMMANDS,
        # "DW": WASHING_MACHINE_HDH_COMMANDS,
        # "MDH": WASHING_MACHINE_HDH_COMMANDS,
        "KBS": WASHING_MACHINE_KBS_COMMANDS,
        "LM": WASHING_MACHINE_KBS_COMMANDS,
        "LMS": WASHING_MACHINE_KBS_COMMANDS
    },
    str(DEVICE_TYPE_AIRPURIFIER): {
    }
}

SUPPLEMENTAL_COMMANDS = {
    str(DEVICE_TYPE_CLIMATE): {
        "PXGD": CLIMATE_PXGD_SUPPLEMENTAL_COMMANDS,
        "VX": CLIMATE_VX_SUPPLEMENTAL_COMMANDS,
        "UX": CLIMATE_UX_SUPPLEMENTAL_COMMANDS,
        "UJ": CLIMATE_UJ_SUPPLEMENTAL_COMMANDS,
        "UK": CLIMATE_UK_SUPPLEMENTAL_COMMANDS,
        "uk": CLIMATE_UK_SUPPLEMENTAL_COMMANDS,
    },
    str(DEVICE_TYPE_WASHING_MACHINE): {
        "HDH": WASHING_MACHINE_HDH_SUPPLEMENTAL_COMMANDS,

        # DDH/DW/MDH 與 HDH 過去共用舊式 extra commands，但本次只遠端確認 NA-V160HDH；
        # 未確認 model 先不要套 supplemental，避免把非主包 key 放回常態輪詢。
        # "DDH": WASHING_MACHINE_HDH_SUPPLEMENTAL_COMMANDS,
        # "DW": WASHING_MACHINE_HDH_SUPPLEMENTAL_COMMANDS,
        # "MDH": WASHING_MACHINE_HDH_SUPPLEMENTAL_COMMANDS,
    }
}

EXCESS_COMMANDS = {
    str(DEVICE_TYPE_CLIMATE): {
        "J-DUCT": [CLIMATE_SWING_VERTICAL_LEVEL, CLIMATE_SWING_HORIZONTAL_LEVEL],
    },
    str(DEVICE_TYPE_DEHUMIDIFIER): {
    },
    str(DEVICE_TYPE_ERV): {
    },
    str(DEVICE_TYPE_DRYER): {
    },
    str(DEVICE_TYPE_FRIDGE): {
    },
    str(DEVICE_TYPE_LIGHT): {
    },
    str(DEVICE_TYPE_WASHING_MACHINE): {
        "HDH": WASHING_MACHINE_HDH_NON_COMMANDLIST_COMMANDS,
    },
    str(DEVICE_TYPE_AIRPURIFIER): {
    }
}

SET_COMMAND_TYPE = {
    str(DEVICE_TYPE_AIRPURIFIER): {
        AIRPURIFIER_POWER: 0,
        AIRPURIFIER_OPERATING_MODE: 1,
        AIRPURIFIER_NANOEX: 135,
        AIRPURIFIER_PET_MODE: 85,
        AIRPURIFIER_LIGHT: 86,
        AIRPURIFIER_BUZZER: 87
    },
    str(DEVICE_TYPE_CLIMATE): {
        CLIMATE_PRESET_MODE: 1,
        CLIMATE_TARGET_TEMPERATURE: 3,
        CLIMATE_SLEEP_MODE: 5,
        CLIMATE_FUZZY_MODE: 135,
        CLIMATE_AIRFRESH_MODE: 136,
        CLIMATE_ANTI_MILDEW: 23,
        CLIMATE_BUZZER: 30,
        CLIMATE_POWER: 128,
        CLIMATE_OPERATING_MODE: 129,
        CLIMATE_FAN_SPEED: 130,
        CLIMATE_ECO: 155,
        CLIMATE_TIMER_ON: 139,
        CLIMATE_TIMER_OFF: 140,
        CLIMATE_SWING_MODE: 143,
        CLIMATE_SWING_VERTICAL_LEVEL: 143,
        CLIMATE_SWING_HORIZONTAL_LEVEL: 145,
        CLIMATE_ACTIVITY: 153,
        CLIMATE_BOOST: 154,
        CLIMATE_AUTO_CLEAN: 152,
        CLIMATE_INDICATOR_LIGHT: 159,
        CLIMATE_MONITOR_MILDEW: 211,
        CLIMATE_IMMEDIATE_MILDEW_DRY: 213,
        CLIMATE_VOICE: 217
    },
    str(DEVICE_TYPE_DEHUMIDIFIER): {
        DEHUMIDIFIER_POWER: 128,
        DEHUMIDIFIER_MODE: 129,
        DEHUMIDIFIER_TARGET_HUMIDITY: 132,
        DEHUMIDIFIER_FAN_SPEED: 137,
        DEHUMIDIFIER_AIRFRESH_MODE: 141,
        DEHUMIDIFIER_FAN_MODE: 142,
        DEHUMIDIFIER_BUZZER: 152,
        DEHUMIDIFIER_TIMER_ON: 213
    },
    str(DEVICE_TYPE_DRYER): {
        ERV_POWER: 0
    },
    str(DEVICE_TYPE_ERV): {
        DRYER_POWER: 0
    },
    str(DEVICE_TYPE_LIGHT): {
        LIGHT_POWER: 0,
        LIGHT_OPERATION_STATE: 112,
        LIGHT_CHANNEL_1_TIMER_ON: 113,
        LIGHT_CHANNEL_1_TIMER_OFF: 114,
        LIGHT_MAINTAIN_MODE: 115,
        LIGHT_CHANNEL_2_TIMER_ON: 116,
        LIGHT_CHANNEL_2_TIMER_OFF: 117,
        LIGHT_CHANNEL_3_TIMER_ON: 118,
        LIGHT_CHANNEL_3_TIMER_OFF: 119
    },
    str(DEVICE_TYPE_WASHING_MACHINE): {
        WASHING_MACHINE_ENABLE: 1,
        WASHING_MACHINE_TIMER: 20,
        WASHING_MACHINE_PROGRESS: 130,
        WASHING_MACHINE_60: 96,
        WASHING_MACHINE_POSTPONE_DRYING_TIME: 97,
        WASHING_MACHINE_PROGRESS_NEW: 100,
        WASHING_MACHINE_WARM_WATER: 105
    },
    str(DEVICE_TYPE_FRIDGE): {
        FRIDGE_FREEZER_MODE: 0,
        FRIDGE_CHAMBER_MODE: 1,
        FRIDGE_FREEZER_TEMPERATURE: 3,
        FRIDGE_CHAMBER_TEMPERATURE: 5,
        FRIDGE_ECO: 12,
        FRIDGE_ERROR_CODE: 14,
        FRIDGE_ENERGY: 19,
        FRIDGE_DEFROST_SETTING: 80,
        FRIDGE_STOP_ICE_MAKING: 82,
        FRIDGE_FAST_ICE_MAKING: 83,
        FRIDGE_FRESH_QUICK_FREZZE: 86,
        FRIDGE_THAW_MODE: 87,
        FRIDGE_THAW_TEMPERATURE: 88,
        FRIDGE_WINTER_MDOE: 90,
        FRIDGE_SHOPPING_MODE: 91,
        FRIDGE_GO_OUT_MODE: 92,
        FRIDGE_NANOEX: 97,
        FRIDGE_ERROR_CODE_JP: 99
    }
}

CAPABILITY_REGISTRY = build_capability_registry(
    commands_type=COMMANDS_TYPE,
    extra_commands=EXTRA_COMMANDS,
    supplemental_commands=SUPPLEMENTAL_COMMANDS,
    excess_commands=EXCESS_COMMANDS,
    set_command_type=SET_COMMAND_TYPE,
    range_family={
        str(DEVICE_TYPE_CLIMATE): CLIMATE_RANGE_FAMILY,
    },
    command_name_overrides=COMMAND_NAME_OVERRIDES,
    command_range_overrides=COMMAND_RANGE_OVERRIDES,
)


SAA_BINARY_SENSORS = {
    DEVICE_TYPE_AIRPURIFIER: AIRPURIFIER_BINARY_SENSORS,
    DEVICE_TYPE_CLIMATE: CLIMATE_BINARY_SENSORS,
    DEVICE_TYPE_DEHUMIDIFIER: DEHUMIDIFIER_BINARY_SENSORS,
    DEVICE_TYPE_DRYER: DRYER_BINARY_SENSORS,
    DEVICE_TYPE_ERV: ERV_BINARY_SENSORS,
    DEVICE_TYPE_FRIDGE: FRIDGE_BINARY_SENSORS,
    DEVICE_TYPE_LIGHT: LIGHT_BINARY_SENSORS,
    DEVICE_TYPE_WASHING_MACHINE: WASHING_MACHINE_BINARY_SENSORS
}

SAA_NUMBERS = {
    DEVICE_TYPE_CLIMATE: CLIMATE_NUMBERS,
    DEVICE_TYPE_DEHUMIDIFIER: DEHUMIDIFIER_NUMBERS,
    DEVICE_TYPE_DRYER: DRYER_NUMBERS,
    DEVICE_TYPE_ERV: ERV_NUMBERS,
    DEVICE_TYPE_LIGHT: LIGHT_NUMBERS
}

SAA_SELECTS = {
    DEVICE_TYPE_AIRPURIFIER: AIRPURIFIER_SELECTS,
    DEVICE_TYPE_CLIMATE: CLIMATE_SELECTS,
    DEVICE_TYPE_DEHUMIDIFIER: DEHUMIDIFIER_SELECTS,
    DEVICE_TYPE_DRYER: DRYER_SELECTS,
    DEVICE_TYPE_ERV: ERV_SELECTS,
    DEVICE_TYPE_FRIDGE: FRIDGE_SELECTS
}

SAA_SENSORS = {
    DEVICE_TYPE_AIRPURIFIER: AIRPURIFIER_SENSORS,
    DEVICE_TYPE_CLIMATE: CLIMATE_SENSORS,
    DEVICE_TYPE_DEHUMIDIFIER: DEHUMIDIFIER_SENSORS,
    DEVICE_TYPE_DRYER: DRYER_SENSORS,
    DEVICE_TYPE_ERV: ERV_SENSORS,
    DEVICE_TYPE_FRIDGE: FRIDGE_SENSORS,
    DEVICE_TYPE_LIGHT: LIGHT_SENSORS
}

SAA_SWITCHES = {
    DEVICE_TYPE_AIRPURIFIER: AIRPURIFIER_SWITCHES,
    DEVICE_TYPE_CLIMATE: CLIMATE_SWITCHES,
    DEVICE_TYPE_DEHUMIDIFIER: DEHUMIDIFIER_SWITCHES,
    DEVICE_TYPE_FRIDGE: FRIDGE_SWITCHES,
    DEVICE_TYPE_LIGHT: LIGHT_SWITCHES
}
